language: generic
sudo: required
dist: trusty

install: sudo ./install-dependencies.sh
script:
  - ansible-playbook -i "localhost," -c local provisioning/playbook.yml --syntax-check
  - ansible-playbook -i "localhost," -c local provisioning/playbook.yml
after_script: curl http://localhost:5000
