language: generic
sudo: required
dist: trusty

install: sudo ./install-dependencies.sh
script:
  - ansible-playbook -i "localhost," -c local provisioning/playbook.yml --syntax-check
  - ansible-playbook -i "localhost," -c local provisioning/playbook.yml
  - sleep 10 && curl -sSf http://localhost:5000
