---
- hosts: all

  sudo: yes

  vars:
    - db_name: ckan_default
    - db_user: ckan_default
    - db_password: ckan_default
    - ckan_package_filename: 'python-ckan_2.0_amd64.deb'
    - ckan_version: 'ckan-2.3'
    - ckan_path: '/usr/lib/ckan/default'
    - paster: '{{ ckan_path }}/bin/paster -c /etc/ckan/default/development.ini'

  tasks:
    # General configuration
    - name: Update apt cache
      apt: update_cache=yes

    - name: Install necessities and nice-to-haves
      apt: pkg={{ item }} state=installed
      with_items:
        - git-core
        - openjdk-6-jdk
        - postgresql
        - python-dev
        - python-pip
        - python-virtualenv
        - solr-jetty
        - supervisor
        - vim

    - name: Enable passwordless sudo
      lineinfile: 'dest=/etc/sudoers regexp="sudo ALL=NOPASSWD: ALL" line="%sudo ALL=NOPASSWD: ALL" state=present'

    # CKAN Instalation
    - name: Create symlink for /etc/ckan
      file: src=/vagrant/ckan/etc dest=/etc/ckan state=link

    - name: Create symlink for /usr/lib/ckan
      file: src=/vagrant/ckan/lib dest=/usr/lib/ckan state=link

    - name: Install CKAN PIP package
      pip: name='git+https://github.com/ckan/ckan.git@ckan-2.3#egg=ckan'

    - name: Install CKAN dependencies
      pip: requirements={{ ckan_path }}/src/ckan/requirements.txt virtualenv={{ ckan_path }}

    # Postgres
    - name: Ensure CKAN database is created
      postgresql_db: 'name={{ db_name }}'
      sudo_user: postgres

    - name: Ensure CKAN database user can access CKAN database
      postgresql_user: 'db={{ db_name }} name={{ db_user }} password={{ db_password }} priv=ALL'
      sudo_user: postgres

    - name: Minimise CKAN database user priveliges
      postgresql_user: 'name={{ db_user }} role_attr_flags=NOSUPERUSER,NOCREATEROLE,NOCREATEDB'
      sudo_user: postgres

    # Jetty
    - name: Jetty settings
      lineinfile: dest=/etc/default/jetty regexp="^NO_START" line="NO_START=0"
    - lineinfile: dest=/etc/default/jetty regexp="^JETTY_HOST" line="JETTY_HOST=127.0.0.1"
    - lineinfile: dest=/etc/default/jetty regexp="^JETTY_PORT" line="JETTY_PORT=8983"

    - name: Remove old configuration settings
      file: path=/etc/solr/conf/schema.xml state=absent

    - name: Link new configuration settings
      file: src=/usr/lib/ckan/default/src/ckan/ckan/config/solr/schema.xml dest=/etc/solr/conf/schema.xml state=link

    - name: Start Jetty service
      service: name=jetty state=started

    # Other
    - name: Setup database
      command: {{ paster }} db init
